apiVersion: apps/v1
kind: Deployment
metadata:
  name: appseai-docs
  namespace: appseai-wfa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appseai-docs
  template:
    metadata:
      labels:
        app: appseai-docs
    spec:
      containers:
        - name: appseai-docs
          image: appseaiacr.azurecr.io/appseai-doc:latest  # <-- your image here
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "768Mi"
              cpu: "759m"
            requests:
              memory: "384Mi"
              cpu: "256m"
          readinessProbe:
            httpGet:
              path: /platform/appse-ai
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /platform/appse-ai
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 30